var _=Object.defineProperty;var E=(e,t)=>_(e,"name",{value:t,configurable:!0});const express=require("express"),db=require("../db"),{rebuildAll}=require("../graph/rebuild"),{ENTITY_TYPES,workflowEntityId,parseEntityId}=require("../graph/entityId"),router=express.Router(),MAX_LOCAL_GRAPH_ROWS=2e3,DEFAULT_PAGE_LIMIT=200,MAX_PAGE_LIMIT=1e3,MAX_SCAN_BATCHES=10;function toApiEntity(e,t){return{id:e.id,type:e.type,label:e.label,ownerId:e.owner_id,meta:e.meta?JSON.parse(e.meta):null,degree:t,createdAt:e.created_at,updatedAt:e.updated_at}}E(toApiEntity,"toApiEntity");function visibleWorkflowIds(e){const t=db.prepare("SELECT id, owner_id, meta FROM entities WHERE type = 'workflow'").all(),s=new Set;for(const r of t){if(r.owner_id===e){s.add(r.id);continue}try{JSON.parse(r.meta||"{}").visibility==="team"&&s.add(r.id)}catch{}}return s}E(visibleWorkflowIds,"visibleWorkflowIds");function containerWorkflowId(e){if(e.type===ENTITY_TYPES.WORKFLOW)return e.id;if(e.type===ENTITY_TYPES.NODE_INSTANCE){const{localId:t}=parseEntityId(e.id);return workflowEntityId(t.slice(0,t.indexOf(":")))}return null}E(containerWorkflowId,"containerWorkflowId");function isVisible(e,t){const s=containerWorkflowId(e);return s===null||t.has(s)}E(isVisible,"isVisible");function degreeOf(e){return db.prepare("SELECT COUNT(*) c FROM edges WHERE source_id = ? OR target_id = ?").get(e,e).c}E(degreeOf,"degreeOf"),router.get("/",(e,t)=>{const{type:s,owner:r}=e.query,n=Math.min(MAX_PAGE_LIMIT,Math.max(1,parseInt(e.query.limit,10)||DEFAULT_PAGE_LIMIT)),l=e.query.cursor?parseInt(e.query.cursor,10):0,d=r==="me"?e.user.id:r,a=visibleWorkflowIds(e.user.id),c=[];let u=l;const p=Math.max(n,DEFAULT_PAGE_LIMIT);for(let o=0;o<MAX_SCAN_BATCHES&&c.length<n;o++){const R=["e.rowid > ?"],h=[u];s&&(R.push("e.type = ?"),h.push(s)),d&&(R.push("e.owner_id = ?"),h.push(d)),h.push(p);const I=db.prepare(`
      SELECT e.*, e.rowid AS _rowid FROM entities e WHERE ${R.join(" AND ")}
      ORDER BY e.rowid ASC LIMIT ?
    `).all(...h);if(!I.length)break;u=I[I.length-1]._rowid;for(const O of I){if(c.length>=n)break;isVisible(O,a)&&c.push(O)}if(I.length<p)break}const g=c.map(()=>"?").join(","),f=c.map(o=>o.id),i=f.length?db.prepare(`SELECT * FROM edges WHERE source_id IN (${g}) AND target_id IN (${g})`).all(...f,...f):[];t.json({entities:c.map(o=>toApiEntity(o,degreeOf(o.id))),edges:i.map(o=>({id:o.id,sourceId:o.source_id,targetId:o.target_id,relation:o.relation})),nextCursor:c.length===n?String(u):null})}),router.get("/local/:entityId",(e,t)=>{const{entityId:s}=e.params,r=Math.min(3,Math.max(1,parseInt(e.query.depth,10)||1)),n=db.prepare("SELECT * FROM entities WHERE id = ?").get(s);if(!n)return t.status(404).json({error:"Kh\xF4ng t\xECm th\u1EA5y entity"});const l=visibleWorkflowIds(e.user.id);if(!isVisible(n,l))return t.status(403).json({error:"Kh\xF4ng c\xF3 quy\u1EC1n xem entity n\xE0y"});const d=db.prepare(`
    WITH RECURSIVE bfs(id, depth) AS (
      SELECT ?, 0
      UNION
      SELECT CASE WHEN e.source_id = bfs.id THEN e.target_id ELSE e.source_id END, bfs.depth + 1
      FROM edges e JOIN bfs ON (e.source_id = bfs.id OR e.target_id = bfs.id)
      WHERE bfs.depth < ?
    )
    SELECT id, MIN(depth) AS depth FROM bfs GROUP BY id LIMIT ?
  `).all(s,r,MAX_LOCAL_GRAPH_ROWS),a=new Map(d.map(i=>[i.id,i.depth])),u=d.map(i=>db.prepare("SELECT * FROM entities WHERE id = ?").get(i.id)).filter(Boolean).filter(i=>isVisible(i,l)),p=new Set(u.map(i=>i.id)),g=[...p].map(()=>"?").join(","),f=p.size?db.prepare(`SELECT * FROM edges WHERE source_id IN (${g}) AND target_id IN (${g})`).all(...p,...p):[];t.json({entities:u.map(i=>({...toApiEntity(i,degreeOf(i.id)),depth:a.get(i.id)})),edges:f.map(i=>({id:i.id,sourceId:i.source_id,targetId:i.target_id,relation:i.relation}))})}),router.get("/backlinks/:entityId",(e,t)=>{const{entityId:s}=e.params,r=db.prepare("SELECT * FROM entities WHERE id = ?").get(s);if(!r)return t.status(404).json({error:"Kh\xF4ng t\xECm th\u1EA5y entity"});const n=visibleWorkflowIds(e.user.id);if(!isVisible(r,n))return t.status(403).json({error:"Kh\xF4ng c\xF3 quy\u1EC1n xem entity n\xE0y"});const l=db.prepare(`
    SELECT ed.relation, src.* FROM edges ed
    JOIN entities src ON src.id = ed.source_id
    WHERE ed.target_id = ?
  `).all(s),d={};for(const a of l)isVisible(a,n)&&(d[a.relation]||(d[a.relation]=[]),d[a.relation].push(toApiEntity(a,degreeOf(a.id))));t.json(d)}),router.post("/rebuild",(e,t)=>{if(e.user.role!=="admin")return t.status(403).json({error:"Ch\u1EC9 admin m\u1EDBi rebuild \u0111\u01B0\u1EE3c graph index"});const s={entities:db.prepare("SELECT COUNT(*) c FROM entities").get().c,edges:db.prepare("SELECT COUNT(*) c FROM edges").get().c},{workflowsIndexed:r}=rebuildAll(),n={entities:db.prepare("SELECT COUNT(*) c FROM entities").get().c,edges:db.prepare("SELECT COUNT(*) c FROM edges").get().c};t.json({workflowsIndexed:r,before:s,after:n})}),module.exports=router;
