var p=Object.defineProperty;var a=(t,e)=>p(t,"name",{value:e,configurable:!0});const express=require("express"),path=require("path"),fs=require("fs"),{spawn,execSync}=require("child_process"),{readAutoUpdateConfig,writeAutoUpdateConfig}=require("../config/agentConfig"),{findPythonExe}=require("../utils/pythonExe"),router=express.Router(),ROOT_DIR=path.join(__dirname,"..",".."),PRODUCT_REPO_URL="https://github.com/Datpt-pce/space-flow-product.git";function isAgentClone(t){try{return execSync("git remote get-url origin",{cwd:t,encoding:"utf8",stdio:["ignore","pipe","ignore"],windowsHide:!0}).trim()===PRODUCT_REPO_URL}catch{return!1}}a(isAgentClone,"isAgentClone");const ALL_TARGETS=[{label:"root",dir:ROOT_DIR},{label:"frontend",dir:path.join(ROOT_DIR,"frontend")},{label:"backend",dir:path.join(ROOT_DIR,"backend")}];function availableTargets(){return ALL_TARGETS.filter(t=>fs.existsSync(path.join(t.dir,"package.json")))}a(availableTargets,"availableTargets");function runCmd(t,e,o,r){return new Promise((i,n)=>{const s=spawn(t,e,{cwd:o,shell:!0,windowsHide:!0});let c="";const d=a(l=>{c+=l.toString();const u=c.split(`
`);c=u.pop();for(const g of u)r(g.replace(/\r$/,""))},"handle");s.stdout.on("data",d),s.stderr.on("data",d),s.on("close",l=>{if(c&&r(c.replace(/\r$/,"")),l!==0)return n(new Error(`${t} ${e.join(" ")} exited with code ${l} (${o})`));i()}),s.on("error",n)})}a(runCmd,"runCmd");function runNpmUpdate(t,e){return runCmd("npm",["update"],t,e)}a(runNpmUpdate,"runNpmUpdate");const PYTHON_PACKAGES=["rembg","Pillow","requests","certifi","google-cloud-storage","yt-dlp","curl_cffi","gdown==6.1.0","faster-whisper==1.2.1","numpy"];function scheduleSelfRestart(t){const e=path.join(t,"backend"),o=`
    setTimeout(() => {
      require('child_process').spawn(process.execPath, ['server.js'], {
        cwd: ${JSON.stringify(e)},
        detached: true,
        stdio: 'ignore',
        windowsHide: true,
      }).unref();
      process.exit(0);
    }, 2000);
  `;spawn(process.execPath,["-e",o],{cwd:e,detached:!0,stdio:"ignore",windowsHide:!0}).unref(),setTimeout(()=>process.exit(0),500)}a(scheduleSelfRestart,"scheduleSelfRestart");function readVersionInfo(){let t=null;try{t=JSON.parse(fs.readFileSync(path.join(ROOT_DIR,"VERSION.json"),"utf8")).version}catch{return{version:null,notes:""}}let e="";try{const r=fs.readFileSync(path.join(ROOT_DIR,"CHANGELOG.md"),"utf8").split(/\n(?=## )/).find(i=>i.trim().startsWith("## "));r&&(e=r.split(`
`).slice(1).join(`
`).trim())}catch{}return{version:t,notes:e}}a(readVersionInfo,"readVersionInfo"),router.get("/version",(t,e)=>{e.json(readVersionInfo())}),router.get("/status",(t,e)=>{const o=availableTargets(),r=require("../agent/releases/client").configured();e.json({available:r||o.length===ALL_TARGETS.length,targets:o.map(i=>i.label),canUpdateCode:r||isAgentClone(ROOT_DIR),version:readVersionInfo().version,agentUpdate:process.env.CENTRAL_SERVER_URL?{...require("../agent/releases/state").status(),signedUpdates:r}:null})});async function runUpdatePipeline(t){if(require("../agent/releases/client").configured())return require("../agent/releases/client").check({onLog:a(n=>t("agent",n),"onLog")});if(process.env.SF_AGENT_RUNNING_RELEASE)throw new Error("Signed Agent requires trusted release configuration");if(process.env.CENTRAL_SERVER_URL&&require("../agent/releases/activity").busy())throw new Error("Agent \u0111ang b\u1EADn; ch\u1EDD ho\xE0n t\u1EA5t c\xF4ng vi\u1EC7c tr\u01B0\u1EDBc khi c\u1EADp nh\u1EADt");const e=availableTargets();if(!require("../agent/releases/client").configured()&&e.length<ALL_TARGETS.length)throw Object.assign(new Error("Ch\u1EC9 kh\u1EA3 d\u1EE5ng khi backend, frontend v\xE0 root c\xF9ng n\u1EB1m tr\xEAn m\u1ED9t m\xE1y (dev native), kh\xF4ng d\xF9ng \u0111\u01B0\u1EE3c trong container product."),{target:"update"});const o=isAgentClone(ROOT_DIR);if(o){t("git","=== git fetch + reset --hard origin/main ===");try{await runCmd("git",["fetch","origin"],ROOT_DIR,n=>t("git",n)),await runCmd("git",["reset","--hard","origin/main"],ROOT_DIR,n=>t("git",n))}catch(n){throw Object.assign(new Error(n.message),{target:"git"})}}let r=null;const i=findPythonExe(ROOT_DIR);if(i){t("python",`=== pip install --upgrade (${i}) ===`);try{await runCmd(i,["-m","pip","install","--upgrade",...PYTHON_PACKAGES],ROOT_DIR,n=>t("python",n))}catch(n){r=`L\u1ED7i c\u1EADp nh\u1EADt th\u01B0 vi\u1EC7n Python (${n.message})`,t("python",`${r} \u2014 b\u1ECF qua, kh\xF4ng ch\u1EB7n ph\u1EA7n c\xF2n l\u1EA1i.`)}}else r="Kh\xF4ng t\xECm th\u1EA5y Python tr\xEAn m\xE1y n\xE0y \u2014 th\u01B0 vi\u1EC7n Python (yt-dlp...) ch\u01B0a \u0111\u01B0\u1EE3c c\u1EADp nh\u1EADt.",t("python",r);for(const n of e){t(n.label,`=== npm update (${n.label}) ===`);try{await runNpmUpdate(n.dir,s=>t(n.label,s))}catch(s){throw Object.assign(new Error(s.message),{target:n.label})}}return{pullCode:o,pythonWarning:r}}a(runUpdatePipeline,"runUpdatePipeline"),router.post("/update-deps",async(t,e)=>{const o=availableTargets();if(!require("../agent/releases/client").configured()&&o.length<ALL_TARGETS.length)return e.status(400).json({error:"Ch\u1EC9 kh\u1EA3 d\u1EE5ng khi backend, frontend v\xE0 root c\xF9ng n\u1EB1m tr\xEAn m\u1ED9t m\xE1y (dev native), kh\xF4ng d\xF9ng \u0111\u01B0\u1EE3c trong container product."});e.setHeader("Content-Type","text/event-stream"),e.setHeader("Cache-Control","no-cache"),e.setHeader("Connection","keep-alive");const r=a((n,s)=>e.write(`event: ${n}
data: ${JSON.stringify(s)}

`),"send");let i;try{i=await runUpdatePipeline((n,s)=>r("log",{target:n,line:s}))}catch(n){r("error",{target:n.target||"update",error:n.message}),e.end();return}if(i.pullCode){r("log",{target:"restart",line:"Code \u0111\xE3 c\u1EADp nh\u1EADt \u2014 agent s\u1EBD t\u1EF1 kh\u1EDFi \u0111\u1ED9ng l\u1EA1i..."}),r("done",{success:!0,restarting:!0,pythonWarning:i.pythonWarning||null}),e.end(),scheduleSelfRestart(ROOT_DIR);return}r("done",{success:!0,restarting:!!i.restarting,pythonWarning:i.pythonWarning||null}),e.end()}),router.get("/auto-update-config",(t,e)=>{e.json(readAutoUpdateConfig())}),router.post("/auto-update-config",(t,e)=>{const{enabled:o,windowStart:r,windowEnd:i}=t.body;if(typeof o!="boolean")return e.status(400).json({error:"enabled ph\u1EA3i l\xE0 boolean"});const n=r!=null,s=i!=null;if(n!==s)return e.status(400).json({error:"C\u1EA7n nh\u1EADp \u0111\u1EE7 c\u1EA3 gi\u1EDD b\u1EAFt \u0111\u1EA7u v\xE0 k\u1EBFt th\xFAc, ho\u1EB7c \u0111\u1EC3 tr\u1ED1ng c\u1EA3 hai."});const c=/^([01]\d|2[0-3]):[0-5]\d$/;if(n&&(!c.test(r)||!c.test(i)))return e.status(400).json({error:"\u0110\u1ECBnh d\u1EA1ng gi\u1EDD kh\xF4ng h\u1EE3p l\u1EC7 (HH:MM)."});e.json(writeAutoUpdateConfig({enabled:o,windowStart:r??null,windowEnd:i??null}))}),router.internals={isAgentClone,runUpdatePipeline,scheduleSelfRestart,ROOT_DIR},module.exports=router;
