import { useState } from 'react';
import { Activity, BarChart3, Clock3, Cpu, TrendingUp, Users } from 'lucide-react';
import { adminApi, useAdminData, AdminHeading, AdminMessage, AdminEmpty, dateLabel } from './AdminShared.jsx';
import './analytics.css';

const names={canvas:'Canvas',video:'Video Editor',batch:'Batch Lab',sheet:'Sheet',graph:'Graph',assistant:'Creative Assistant',admin:'Admin Console'};
const number=n=>n==null?'Chưa đo':new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(n);
const seconds=n=>n==null?'Chưa đo':n<1000?`${number(n)} ms`:`${number(n/1000)} s`;
const minutes=n=>`${number(n/60000)} phút`;
const mib=n=>n==null?'Chưa đo':`${number(n/1024**2)} MiB`;
const percent=(a,b)=>b?`${number(a/b*100)}%`:'Chưa có mẫu';
function Metric({label,value,hint,icon:Icon=Activity}){return <article className="analytics-metric"><span><Icon size={16}/>{label}</span><strong>{value}</strong><small>{hint}</small></article>;}
function Chart({title,rows,lines,format=number,forecast=false}) {
  const [hover,setHover]=useState(null);
  const values=rows.flatMap(r=>lines.map(l=>r[l.key])).filter(Number.isFinite),max=Math.max(1,...values),width=780,height=210,pad=38;
  const x=i=>pad+i*(width-pad*2)/Math.max(1,rows.length-1),y=v=>height-pad-(v/max)*(height-pad*2);
  const selected=hover===null?null:rows[hover];
  return <section className="review-card analytics-chart"><div className="review-section-heading"><h3>{title}</h3><div className="analytics-legend">{lines.map(l=><span key={l.key}><i style={{background:l.color}}/>{l.label}</span>)}</div></div>
    {rows.length?<><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={title} onMouseLeave={()=>setHover(null)} onMouseMove={event=>{
      const r=event.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(rows.length-1,Math.round(((event.clientX-r.left)/r.width*width-pad)/(width-pad*2)*(rows.length-1)))));
    }}>
      <title>{title}; bảng dữ liệu ở bên dưới biểu đồ</title>
      {[0,.5,1].map(t=><g key={t}><line x1={pad} x2={width-pad} y1={y(max*t)} y2={y(max*t)} className="analytics-grid"/><text x={pad-8} y={y(max*t)+4} textAnchor="end">{format(max*t)}</text></g>)}
      {lines.map(l=><g key={l.key}><path d={rows.map((r,i)=>Number.isFinite(r[l.key])?`${i>0&&Number.isFinite(rows[i-1][l.key])?'L':'M'}${x(i)},${y(r[l.key])}`:'').join(' ')} fill="none" stroke={l.color} strokeWidth="2.5" strokeDasharray={forecast&&l.key!=='observed'?'6 5':undefined}/>
        {rows.map((r,i)=>Number.isFinite(r[l.key])&&<circle key={i} cx={x(i)} cy={y(r[l.key])} r="4" fill={l.color}/>)}</g>)}
      <text x={pad} y={height-8}>{rows[0].day}</text><text x={width-pad} y={height-8} textAnchor="end">{rows.at(-1).day}</text>
      {selected&&<line x1={x(hover)} x2={x(hover)} y1={pad} y2={height-pad} stroke="currentColor" strokeDasharray="3 3"/>}
    </svg><p className="analytics-chart-readout">{selected?`${selected.day} · ${lines.map(l=>`${l.label}: ${format(selected[l.key])}`).join(' · ')}`:'Di chuột để xem từng ngày. Ngày thiếu coverage chưa thể coi là không sử dụng.'}</p>
      <details><summary>Xem bảng dữ liệu</summary><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Ngày UTC</th>{lines.map(l=><th key={l.key}>{l.label}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.day}><td>{r.day}</td>{lines.map(l=><td key={l.key}>{format(r[l.key])}</td>)}</tr>)}</tbody></table></div></details></>:<AdminEmpty>Chưa có lịch sử để vẽ biểu đồ.</AdminEmpty>}
  </section>;
}
function Overview({data}) {
  const o=data.overview,clockLabels={visible:'Tab đang hiển thị',focused:'Tab có focus',pointer:'Con trỏ bên trong',engaged:'Tương tác gần đây',viewing:'Đang xem video',waiting:'Chờ workflow khi có focus'};
  return <><div className="analytics-metrics">
    <Metric label="User hoạt động 7 ngày" value={number(o.wau)} hint="Có thao tác tính năng được ghi nhận" icon={Users}/>
    <Metric label="Lượt có kết quả thành công" value={percent(o.succeeded,o.terminalJobs)} hint={`${o.succeeded} / ${o.terminalJobs} lượt có kết cục · không phải chất lượng đầu ra`} icon={BarChart3}/>
    <Metric label="Thời gian tương tác" value={minutes(o.clocks.engaged)} hint="Đã khử thời gian trùng giữa các tab" icon={Clock3}/>
    <Metric label="Đầu ra đã bàn giao" value={number(o.deliveredOutputs)} hint={`${o.outcomeUsers} user có delivery thành công`} icon={TrendingUp}/>
  </div><Chart title="Sử dụng theo ngày" rows={data.trend} lines={[{key:'users',label:'User hoạt động',color:'#4f46e5'},{key:'jobs',label:'Lượt xử lý',color:'#0d9488'}]}/>
  <div className="analytics-two"><section className="review-card"><h3>Thời gian sử dụng</h3><p className="review-hint">Các khoảng có thể giao nhau. Không cộng chúng thành tổng thời gian hoặc xem đó là chứng nhận sự chú ý.</p>
    {Object.entries(clockLabels).map(([key,label])=><div className="analytics-bar-row" key={key}><span>{label}</span><div><i style={{width:`${Math.min(100,o.clocks[key]/Math.max(1,o.clocks.visible)*100)}%`}}/></div><strong>{minutes(o.clocks[key])}</strong></div>)}
    <p className="review-hint">Con trỏ: chỉ thiết bị có hover; số 0 cũng có thể do browser không hỗ trợ. Thời gian chờ trên tab hiện áp dụng workflow Canvas.</p></section>
    <section className="review-card"><h3>Kết quả và thời gian chờ</h3><dl className="admin-metrics"><dt>Lượt được nhận</dt><dd>{number(o.jobs)}</dd><dt>Chưa có kết cục</dt><dd>{number(o.jobs-o.terminalJobs)}</dd><dt>Hủy / chưa rõ kết quả</dt><dd>{number(o.states.cancelled||0)} / {number(o.states.unknown||0)}</dd><dt>Chờ hàng đợi · p50 / p95</dt><dd>{seconds(o.queueP50)} / {seconds(o.queueP95)}</dd><dt>Từ bắt đầu đến kết thúc · p95</dt><dd>{seconds(o.runtimeP95)}</dd><dt>Phiên có thao tác</dt><dd>{number(o.sessions)}</dd></dl>
      <p>{number(o.downloads.outputs)} kết quả render đã tải thành công · {number(o.downloads.users)} user. Mỗi kết quả/user chỉ tính lần tải đầu tiên.</p>
      <p className="review-hint">Run thành công chưa chứng minh output hữu ích. Delivery và tải xuống là dấu hiệu sử dụng kết quả; chưa đo chất lượng hay thời gian tiết kiệm so với làm thủ công.</p></section></div>
    <section className="review-card analytics-section"><h3>User quay lại</h3><p className="review-hint">Quay lại đúng ngày D1/D7/D30 từ ngày đầu có thao tác trong lịch sử còn lưu (tối đa 395 ngày). Chỉ tính cohort đã đủ tuổi đến hết hôm qua; áp dụng bộ lọc tính năng/nhóm user, không giới hạn vào khoảng ngày biểu đồ.</p>
      <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Mốc</th><th>User đủ tuổi cohort</th><th>Quay lại</th><th>Tỷ lệ</th></tr></thead><tbody>{data.cohorts.map(c=><tr key={c.day}><td>D{c.day}</td><td>{number(c.eligible)}</td><td>{number(c.returned)}</td><td>{percent(c.returned,c.eligible)}</td></tr>)}</tbody></table></div></section></>;
}
function Features({data}) {
  return <><section className="review-card"><h3>Tính năng được sử dụng</h3><p className="review-hint">Số user trong khoảng đã chọn; không phải tỷ lệ adoption trên số người được cấp quyền. Hoàn tất yêu cầu HTTP chưa phải hoàn tất tác vụ.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Tính năng</th><th>User</th><th>Phiên</th><th>Tương tác</th><th>Chạy / lệnh</th><th>Nhấn lặp</th><th>Làm mới / F5</th></tr></thead><tbody>{data.features.map(f=><tr key={f.feature}><td>{names[f.feature]}</td><td>{f.users}</td><td>{f.sessions}</td><td>{minutes(f.clocks.engaged)}</td><td>{(f.actions.run_clicked||0)+(f.actions.command_requested||0)}</td><td>{f.actions.repeat_action||0}</td><td>{f.actions.data_refresh_clicked||0} / {f.actions.page_reload||0}</td></tr>)}</tbody></table></div>{!data.features.length&&<AdminEmpty>Chưa nhận thao tác từ browser. Dữ liệu xuất hiện khi người dùng tương tác và gửi batch.</AdminEmpty>}</section>
    <section className="review-card analytics-section"><h3>Trải nghiệm từng node</h3><p className="review-hint">Chỉ actual attempts được đo; pinned/disabled và nodeStart trước dispatch không tính. Retry có thể là thử lại hợp lệ. Thao tác sửa/lặp chỉ giữ 30 ngày.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Node</th><th>User / run</th><th>Attempts</th><th>Thành công lần đầu</th><th>Lỗi / hủy</th><th>Retry tự động</th><th>Thời gian p50 / p95</th><th>Sửa / lặp</th></tr></thead><tbody>{data.nodes.map(n=><tr key={n.node}><td><strong>{n.node}</strong></td><td>{n.users} / {n.runs}</td><td>{n.attempts}{n.incomplete>0&&<small> · {n.incomplete} thiếu kết cục</small>}</td><td>{percent(n.firstSuccess,n.firstAttempts)}</td><td>{n.failed} / {n.cancelled}</td><td>{n.retries}</td><td>{seconds(n.p50)} / {seconds(n.p95)}</td><td>{n.friction.node_config_committed||0} / {n.friction.repeat_action||0}</td></tr>)}</tbody></table></div>{!data.nodes.length&&<AdminEmpty>Chưa có lần thực thi node được đo trong khoảng này.</AdminEmpty>}</section></>;
}
function Resources({data}) {
  const r=data.resources,grouped={};for(const row of r.daily){const d=grouped[row.day] ||= {day:row.day,server:null,agent:null};d[row.scope]=(d[row.scope]||0)+row.cpu_seconds;}
  return <><div className="analytics-metrics"><Metric label="Browser · độ trễ p95" value={seconds(r.browser.interactionP95)} hint={`${r.browser.samples} bản ghi hiệu năng · lấy mẫu 10% phiên`} icon={Activity}/><Metric label="Browser · JS heap p95" value={mib(r.browser.heapP95)} hint="Ước lượng JS heap khi trình duyệt hỗ trợ" icon={Cpu}/><Metric label="Browser · long-task / batch p95" value={seconds(r.browser.longTaskP95)} hint="Tổng thời gian tác vụ dài trong một batch" icon={Clock3}/><Metric label="Tiến trình có mẫu gần đây" value={number(r.latest.length)} hint="Mẫu trong giờ gần nhất; xem thời điểm ở bảng" icon={Cpu}/></div>
    <Chart title="CPU đã sử dụng theo ngày · core-seconds" rows={Object.values(grouped)} lines={[{key:'server',label:'Backend',color:'#4f46e5'},{key:'agent',label:'Agent',color:'#0d9488'}]}/>
    <section className="review-card analytics-section"><h3>Backend & Agent · mẫu gần nhất</h3><p className="review-hint">CPU một core có thể vượt 100%. Tiến trình con là mẫu quan sát, có thể bỏ lỡ job ngắn; RAM cây tiến trình là ước lượng. Không gán toàn bộ CPU máy cho từng job.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Nguồn</th><th>Mẫu cuối</th><th>CPU một core</th><th>CPU / capacity</th><th>RAM tiến trình</th><th>Tiến trình con</th><th>RAM con</th><th>Ổ đĩa trống</th></tr></thead><tbody>{r.latest.map(s=><tr key={s.instance}><td>{s.scope==='agent'?'Agent':'Backend'} <small>{s.instanceId.slice(0,8)}</small></td><td>{dateLabel(s.at)}{Date.now()-s.at>60000&&<small> · Mẫu cũ</small>}</td><td>{percent(s.cpuSeconds,s.elapsedMs/1000)}</td><td>{percent(s.cpuSeconds,s.elapsedMs/1000*s.cores)}</td><td>{mib(s.rssBytes)}</td><td>{s.treeSupported?`${s.childCount} · ${number(s.treeCpuSeconds)} core-s`:'Chưa đo'}</td><td>{mib(s.treeRssBytes)}</td><td>{mib(s.diskFreeBytes)}</td></tr>)}</tbody></table></div>{!r.latest.length&&<AdminEmpty>Chưa nhận mẫu tài nguyên. Agent cần bản có hỗ trợ gửi số đo.</AdminEmpty>}</section>
    <section className="review-card analytics-section"><h3>Phạm vi đo</h3><p>Backend là tiến trình API của môi trường đang mở, có thể nằm trên máy cá nhân. Agent là tiến trình đã ghép nối. Hai nhóm được trình bày riêng.</p><p className="review-hint">GPU/VRAM, dịch vụ dùng chung như Ollama/ComfyUI, CPU toàn bộ browser và chi phí provider: chưa đo. Provider hiện chỉ có counters từ adapter, mất khi restart.</p><details><summary>Provider counters hiện tại</summary><pre>{JSON.stringify(r.provider,null,2)}</pre></details></section></>;
}
function Forecasts({data}) {
  return <><p className="review-hint">Dự báo cho toàn môi trường, không áp dụng bộ lọc user/node. Yêu cầu tối thiểu 56 ngày liên tục, mỗi ngày coverage ≥95%, cùng phiên bản và kiểm tra trên các tuần đã qua.</p>{Object.entries(data.forecasts).map(([kind,f])=><section className="review-card analytics-section" key={kind}><h3>{kind==='workflow'?'Lượt workflow':kind==='cpu'?'CPU backend · core-seconds':'Lượt render'} · 7 ngày tới</h3>
    {f.status==='available'?<><p>{f.model==='weekday-mean'?'Trung bình cùng thứ':'Cùng thứ tuần trước'} · dữ liệu đến {f.trainingCutoff} · MAE {number(f.mae)} · WAPE {f.wape==null?'Không xác định':percent(f.wape,1)}</p><Chart title="Dự báo và khoảng bất định" rows={[...f.history.slice(-14).map(r=>({day:r.day,observed:r.value})),...f.points]} forecast lines={[{key:'observed',label:'Đã đo',color:'#0d9488'},{key:'value',label:'Dự báo',color:'#4f46e5'},{key:'lower95',label:'Cận dưới 95%',color:'#94a3b8'},{key:'upper95',label:'Cận trên 95%',color:'#94a3b8'}]}/><p className="review-hint">Coverage kiểm tra 80%: {percent(f.coverage80,1)} · 95%: {percent(f.coverage95,1)} trên {f.validationDays} ngày. Đây là dự đoán, không phải cam kết.</p></>:<div className="analytics-unavailable"><TrendingUp size={30}/><strong>Chưa đủ dữ liệu để dự báo</strong><p>{f.reason}</p><small>Đã có {f.history.filter(d=>d.coverage>=.95).length} / 56 ngày đủ coverage trong cửa sổ hiển thị.</small></div>}
  </section>)}<section className="review-card analytics-section"><h3>Kịch bản tài nguyên và dung lượng</h3><p className="review-hint">{data.disk.reason}</p>{data.disk.status==='scenario'&&<p>Chạm ngưỡng dự phòng {mib(data.disk.reserveBytes)} sau khoảng {number(data.disk.daysToReserve)} ngày · {data.disk.date||'Ngoài chân trời hiển thị'}.</p>}</section></>;
}
export default function AdminAnalytics() {
  const [tab,setTab]=useState('overview'),[days,setDays]=useState('30'),[feature,setFeature]=useState(''),[role,setRole]=useState(''),[node,setNode]=useState(''),[location,setLocation]=useState('');
  const {data,error,loading,refresh}=useAdminData(()=>adminApi(`/admin-console/analytics?${new URLSearchParams({days,feature,role,node:tab==='features'?node:'',location:tab==='features'?location:''})}`),[days,feature,role,node,location,tab],15000);
  const tabs=[['overview','Tổng quan',BarChart3],['features','Tính năng & Node',Users],['resources','Tài nguyên',Cpu],['forecast','Dự báo',TrendingUp]];
  return <section className="admin-page analytics-page"><AdminHeading title="Phân tích dữ liệu" description="Hiểu cách người dùng làm việc, tìm điểm chờ và theo dõi tài nguyên theo thời gian." loading={loading} refresh={refresh}/><AdminMessage error={error}/>
    <div className="analytics-filters"><label>Khoảng thời gian<select value={days} onChange={e=>setDays(e.target.value)}><option value="7">7 ngày</option><option value="30">30 ngày</option><option value="90">90 ngày</option></select></label><label>Tính năng<select value={feature} onChange={e=>setFeature(e.target.value)}><option value="">Tất cả tính năng</option>{Object.entries(names).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Nhóm user<select value={role} onChange={e=>setRole(e.target.value)}><option value="">Tất cả</option><option value="member">Member</option><option value="admin">Admin</option></select></label>
      {tab==='features'&&<><label>Node<input value={node} maxLength={100} onChange={e=>setNode(e.target.value)} placeholder="Ví dụ: text"/></label><label>Nơi chạy<select value={location} onChange={e=>setLocation(e.target.value)}><option value="">Tất cả</option><option value="server">Backend</option><option value="agent">Agent</option><option value="unknown">Chưa xác định</option></select></label></>}</div>
    <div className="analytics-freshness"><span className={`analytics-dot ${!data?.watermark||Date.now()-data.watermark>120000?'is-stale':''}`}/><span>{data?.watermark?`Nhận dữ liệu gần nhất: ${dateLabel(data.watermark)}`:'Chưa có dữ liệu từ collector'} · Ngày báo cáo: UTC</span>{loading&&<span>Đang cập nhật…</span>}</div>
    {data&&!data.enabled&&<AdminMessage notice="Thu thập analytics đang tắt trên môi trường này."/>}{data&&!data.complete&&<AdminMessage notice="Khoảng dữ liệu vượt giới hạn truy vấn. Hãy thu hẹp bộ lọc; kết quả hiện tại chưa đầy đủ."/>}
    <nav className="analytics-tabs" aria-label="Phân tích dữ liệu">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</nav>
    {!data?<AdminEmpty>{loading?'Đang tải báo cáo…':'Không tải được báo cáo. Hãy làm mới để thử lại.'}</AdminEmpty>:tab==='overview'?<Overview data={data}/>:tab==='features'?<Features data={data}/>:tab==='resources'?<Resources data={data}/>:<Forecasts data={data}/>}
  </section>;
}
