const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const crypto = require('crypto');
const { ensureAnalyticsSchema } = require('./schema');
const { createCollector, validate } = require('./collector');
const { queryAnalytics } = require('./query');
const { recordAttempt } = require('./attempts');
const { DAY, duration, dayOf } = require('./math');
const { forecast, diskScenario } = require('./forecast');
const { recordOutputUsage } = require('./outputUsage');
const { parseProcStat, descendants, treeDelta, validSample } = require('./resources');
const db = new DatabaseSync(':memory:');
db.exec(`PRAGMA foreign_keys=ON;
 CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT);
 INSERT INTO users VALUES('member','member'),('admin','admin');
 CREATE TABLE flow_runs(id TEXT PRIMARY KEY,owner_id TEXT,state TEXT,created_at INTEGER,updated_at INTEGER);
 CREATE TABLE node_runs(run_id TEXT,node_id TEXT);
 CREATE TABLE video_render_jobs(id TEXT PRIMARY KEY,owner_id TEXT,status TEXT,created_at TEXT);
 CREATE TABLE video_batch_deliveries(id TEXT PRIMARY KEY,owner_id TEXT,state TEXT,created_at TEXT);`);
ensureAnalyticsSchema(db);ensureAnalyticsSchema(db);
db.exec("ALTER TABLE users ADD COLUMN created_at TEXT DEFAULT '2026-09-11'; ALTER TABLE users ADD COLUMN name TEXT");
const now=Date.parse('2026-09-11T12:00:00Z'),collector=createCollector(db,()=>now);
const e=(name,props={},at=now)=>({id:crypto.randomUUID(),sessionId:'s1',at,feature:'canvas',name,props});
const action=e('run_clicked');
assert.deepEqual(collector.ingest('member',{events:[action,action]}),{accepted:1,duplicates:1});
assert.equal(db.prepare('SELECT COUNT(*) n FROM analytics_events').get().n,1);
assert.throws(()=>validate({events:[{...action,user_id:'admin'}]},now),/Invalid/);
assert.throws(()=>validate({events:[e('run_clicked',{prompt:'secret'})]},now),/Invalid/);
assert.throws(()=>validate({events:[e('performance',{heapBytes:NaN})]},now),/Invalid/);
assert.throws(()=>validate({events:Array(51).fill(action)},now),/Invalid/);
assert.throws(()=>validate({events:[{...action,at:now-DAY-1}]},now),/Invalid/);
assert.throws(()=>collector.ingest('member',{events:[e('undo'),e('bogus')]}),/Invalid/);
assert.equal(db.prepare('SELECT COUNT(*) n FROM analytics_events').get().n,1,'invalid batch writes nothing');
const presence=(start,end)=>e('presence',{start,end,visible:true,focused:true,pointer:false,engaged:true,viewing:false,waiting:false},end);
collector.ingest('member',{events:[presence(now-20000,now-5000),{...presence(now-15000,now),sessionId:'s2'}]});
let report=queryAnalytics(db,{},now);
assert.equal(report.overview.clocks.engaged,20000,'overlapping tab intervals union');
collector.ingest('admin',{events:[presence(now-15000,now)]});
assert.equal(queryAnalytics(db,{},now).overview.clocks.engaged,35000,'different users do not overlap');
assert.equal(queryAnalytics(db,{role:'member'},now).overview.clocks.engaged,20000);
assert.equal(report.overview.activeUsers,1,'presence alone is not semantic DAU');
assert.equal(queryAnalytics(db,{role:'admin'},now).overview.activeUsers,0);
collector.ingest('admin',{events:[{...e('command_completed',{command:'render',durationMs:1}),sessionId:'async-only'}]});
assert.equal(queryAnalytics(db,{role:'admin'},now).overview.activeUsers,0,'async completion is not human activity');
assert.equal(queryAnalytics(db,{},now).trend[0].users,null,'missing history is not zero');
recordOutputUsage(db,'member','render-output');recordOutputUsage(db,'member','render-output');
assert.equal(queryAnalytics(db,{},Date.now()).overview.downloads.outputs,1,'download outcome is idempotent');
assert.equal(queryAnalytics(db,{feature:'canvas'},Date.now()).overview.downloads.outputs,0,'download respects feature');
assert.equal(duration([[1,4],[2,3],[4,8]]),7);
assert.throws(()=>queryAnalytics(db,{days:'999'},now),/Invalid/);
const run=crypto.randomUUID();
db.prepare('INSERT INTO flow_runs VALUES (?,?,?,?,?)').run(run,'member','queued',now-10000,now-10000);
db.prepare('INSERT INTO node_runs VALUES (?,?)').run(run,'text-1');
db.exec('BEGIN');db.prepare("UPDATE flow_runs SET state='running',updated_at=? WHERE id=?").run(now-8000,run);db.exec('ROLLBACK');
assert.equal(db.prepare('SELECT state FROM analytics_jobs WHERE id=?').get(run).state,'queued','transaction rollback includes analytics');
db.prepare("UPDATE flow_runs SET state='running',updated_at=? WHERE id=?").run(now-8000,run);
const aid=crypto.randomUUID(),attempt={id:aid,nodeId:'text-1',nodeType:'text',attempt:1,location:'agent',state:'started'};
recordAttempt(db,run,attempt,now-7000);recordAttempt(db,run,attempt,now-6500);
recordAttempt(db,run,{...attempt,state:'succeeded',durationMs:250},now-6000);
recordAttempt(db,run,{...attempt,state:'failed',durationMs:300},now-5000);
assert.equal(db.prepare('SELECT duration_ms FROM analytics_attempts').get().duration_ms,250,'terminal replay immutable');
db.prepare("UPDATE flow_runs SET state='succeeded',updated_at=? WHERE id=?").run(now,run);
report=queryAnalytics(db,{},now);
assert.equal(report.nodes[0].attempts,1);assert.equal(report.overview.queueP95,2000);assert.equal(report.overview.runtimeP95,8000);
assert.equal(queryAnalytics(db,{feature:'video'},now).nodes.length,0,'Canvas attempts are not Video usage');
assert.equal(report.overview.deliveredOutputs,0,'run success is not delivery');
db.prepare('INSERT INTO video_batch_deliveries VALUES (?,?,?,?)').run('delivery','member','planned','2026-09-11 11:59:00');
db.prepare("UPDATE video_batch_deliveries SET state='done' WHERE id='delivery'").run();
assert.equal(queryAnalytics(db,{},Date.now()).overview.deliveredOutputs,1);
const series=Array.from({length:70},(_,i)=>({day:dayOf(now-(70-i)*DAY),coverage:1,version:'1',value:10+i%7}));
assert.equal(forecast(series).status,'available');
assert.equal(forecast(series.slice(0,20)).status,'insufficient_data');
assert.equal(forecast(series.map((s,i)=>({...s,coverage:i===60?.5:1}))).status,'insufficient_data');
assert.equal(forecast(series.map(s=>({...s,value:0}))).status,'insufficient_data');
assert.equal(forecast(series.map((s,i)=>({...s,version:i===60?'2':'1'}))).status,'insufficient_data');
assert.equal(forecast(series.filter((_,i)=>i!==60)).status,'insufficient_data');
const disks=series.slice(-14).map((s,i)=>({day:s.day,free:30*1024**3-i*1024**3}));
assert.equal(diskScenario(disks).daysToReserve,16);
assert.equal(diskScenario(disks.slice(1)).status,'insufficient_data');
assert.equal(diskScenario(disks.map(s=>({...s,free:30*1024**3}))).status,'not_decreasing');
assert.equal(queryAnalytics(db,{},now+DAY).cohorts[0].eligible,0,'today is not a mature return day');
assert.equal(queryAnalytics(db,{},now+2*DAY).cohorts[0].eligible,1);
const rows=[{pid:1,ppid:0,start:'99',cpu:1,rss:2},{pid:2,ppid:1,start:'100',cpu:3,rss:5},{pid:3,ppid:2,start:'101',cpu:4,rss:6},{pid:4,ppid:1,start:'98',cpu:8,rss:2}];
assert.deepEqual(descendants(rows,1).map(r=>r.pid),[2,3],'exclude PID reused parent');
const delta=treeDelta([{...rows[1],cpu:4},{...rows[2],start:'200',cpu:100}],rows.slice(1,3));
assert.equal(delta.treeCpuSeconds,1,'PID reuse never counts prior lifetime CPU');
const fields=Array(22).fill('0');fields[1]='1';fields[11]='200';fields[12]='100';fields[19]='99';fields[21]='4';
assert.equal(parseProcStat('2 (name with ) bracket) '+fields.join(' '),100,4096).rss,16384);
assert.equal(parseProcStat('2 (name) '+fields.join(' '),100,4096).cpu,3);
assert(!validSample({id:crypto.randomUUID(),instanceId:crypto.randomUUID(),treeSupported:false,elapsedMs:15000,cpuSeconds:1,rssBytes:12,cores:2,path:'secret'}));
db.prepare("UPDATE analytics_settings SET value='0' WHERE key='enabled'").run();
db.prepare('INSERT INTO flow_runs VALUES (?,?,?,?,?)').run('disabled','member','queued',now,now);
assert(!db.prepare("SELECT 1 FROM analytics_jobs WHERE id='disabled'").get());
const begin=performance.now();
for(let i=0;i<40;i++)collector.ingest('member',{events:Array.from({length:50},()=>e('undo'))});
const ingestMs=performance.now()-begin,read=performance.now();queryAnalytics(db,{},now);const queryMs=performance.now()-read;
assert.equal(db.prepare("SELECT COUNT(*) n FROM analytics_events WHERE name='undo'").get().n,2000);
db.prepare("DELETE FROM users WHERE id='member'").run();
assert.equal(db.prepare("SELECT COUNT(*) n FROM analytics_daily WHERE owner_id='member'").get().n,0);
assert.equal(db.prepare("SELECT COUNT(*) n FROM analytics_attempts WHERE owner_id='member'").get().n,0);
db.close();
console.log(JSON.stringify({status:'pass',cases:'collector/auth-boundary/union/rollback/replay/forecast/process-tree/retention-owner',events:2000,ingestMs,queryMs}));
