var h=Object.defineProperty;var s=(e,r)=>h(e,"name",{value:r,configurable:!0});const fs=require("fs"),os=require("os"),path=require("path"),crypto=require("crypto"),AdmZip=require("adm-zip"),db=require("../db"),{verify}=require("./sfpkg"),{installDependencies}=require("./dependencies"),{verifyArchive,getPublicKeyInfo}=require("./signing"),INSTALLS_ROOT=require("../utils/dataPaths").installs;function installDir(e,r){return path.join(INSTALLS_ROOT,e,r)}s(installDir,"installDir");function install({archiveFile:e,installedBy:r=null}){const t=fs.readFileSync(e),n=verify({buffer:t});if(!n.valid)throw new Error(`Refusing to install invalid package: ${n.errors.join("; ")}`);const{packageId:i,version:o}=n.manifest,a=installDir(i,o);fs.mkdirSync(a,{recursive:!0}),new AdmZip(t).extractAllTo(a,!0);try{installDependencies(a)}catch(u){throw fs.rmSync(a,{recursive:!0,force:!0}),new Error(`Dependency installation failed for ${i}@${o}: ${u.message}`)}return db.prepare(`
    INSERT INTO node_installations (id, package_id, version, install_path, checksum, installed_by)
    VALUES (?, ?, ?, ?, ?, ?)
    ON CONFLICT(package_id, version) DO UPDATE SET
      install_path = excluded.install_path,
      checksum = excluded.checksum,
      installed_by = excluded.installed_by,
      installed_at = datetime('now')
  `).run(crypto.randomUUID(),i,o,a,n.checksum,r),{packageId:i,version:o,installPath:a,checksum:n.checksum}}s(install,"install");function installFromPublished({packageId:e,version:r,installedBy:t=null}){const n=db.prepare("SELECT * FROM node_versions WHERE package_id = ? AND version = ? AND status = 'Published'").get(e,r);if(!n)throw new Error(`Kh\xF4ng t\xECm th\u1EA5y version \u0111\xE3 publish: ${e}@${r}`);const i=db.prepare("SELECT signature, key_fingerprint FROM node_signatures WHERE version_id = ?").get(n.id);if(!i)throw new Error(`Version \u0111\xE3 Published nh\u01B0ng kh\xF4ng c\xF3 signature \u2014 d\u1EEF li\u1EC7u kh\xF4ng nh\u1EA5t qu\xE1n: ${e}@${r}`);if(!fs.existsSync(n.archive_path))throw new Error(`Archive kh\xF4ng c\xF2n tr\xEAn \u0111\u0129a: ${e}@${r}`);const o=fs.readFileSync(n.archive_path),{pem:a,fingerprint:c}=getPublicKeyInfo();if(i.key_fingerprint!==c)throw new Error(`Signature k\xFD b\u1EDFi key "${i.key_fingerprint}", kh\xE1c key hi\u1EC7n t\u1EA1i "${c}" \u2014 t\u1EEB ch\u1ED1i c\xE0i`);if(!verifyArchive(o,i.signature,a))throw new Error(`Ch\u1EEF k\xFD kh\xF4ng h\u1EE3p l\u1EC7 cho ${e}@${r} \u2014 archive c\xF3 th\u1EC3 \u0111\xE3 b\u1ECB ch\u1EC9nh s\u1EEDa, t\u1EEB ch\u1ED1i c\xE0i`);if(crypto.createHash("sha256").update(o).digest("hex")!==n.checksum)throw new Error(`Checksum kh\xF4ng kh\u1EDBp cho ${e}@${r} \u2014 t\u1EEB ch\u1ED1i c\xE0i`);const l=path.join(os.tmpdir(),`sf-registry-install-${crypto.randomUUID()}.sfpkg`);fs.writeFileSync(l,o);try{return install({archiveFile:l,installedBy:t})}finally{fs.rmSync(l,{force:!0})}}s(installFromPublished,"installFromPublished");function getInstallation(e,r){return db.prepare("SELECT * FROM node_installations WHERE package_id = ? AND version = ?").get(e,r)}s(getInstallation,"getInstallation");function listInstallations(){return db.prepare("SELECT * FROM node_installations ORDER BY installed_at DESC").all()}s(listInstallations,"listInstallations");function getApprovedPaths(e,r){const t=getInstallation(e,r);if(!t||!t.approved_paths)return[];try{const n=JSON.parse(t.approved_paths);return Array.isArray(n)?n:[]}catch{return[]}}s(getApprovedPaths,"getApprovedPaths");function setApprovedPaths(e,r,t){if(db.prepare("UPDATE node_installations SET approved_paths = ? WHERE package_id = ? AND version = ?").run(JSON.stringify(t),e,r).changes===0)throw new Error(`No installation found for ${e}@${r}`)}s(setApprovedPaths,"setApprovedPaths");function acknowledgeRevocation(e,r){if(db.prepare("UPDATE node_installations SET revocation_acknowledged = 1 WHERE package_id = ? AND version = ?").run(e,r).changes===0)throw new Error(`No installation found for ${e}@${r}`)}s(acknowledgeRevocation,"acknowledgeRevocation"),module.exports={install,installFromPublished,getInstallation,listInstallations,installDir,getApprovedPaths,setApprovedPaths,acknowledgeRevocation};
