var E=Object.defineProperty;var o=(n,e)=>E(n,"name",{value:e,configurable:!0});const crypto=require("crypto"),db=require("../db"),{ENTITY_TYPES,RELATIONS,workflowEntityId,nodeInstanceEntityId,nodePackageEntityId,userEntityId}=require("./entityId"),upsertEntity=db.prepare(`
  INSERT INTO entities (id, type, label, owner_id, meta)
  VALUES (?, ?, ?, ?, ?)
  ON CONFLICT(id) DO UPDATE SET
    label = excluded.label,
    owner_id = excluded.owner_id,
    meta = excluded.meta,
    updated_at = datetime('now')
`),insertEdge=db.prepare("INSERT INTO edges (id, source_id, target_id, relation, meta) VALUES (?, ?, ?, ?, ?)");function withGraphTransaction(n){const e=`sp_${crypto.randomUUID().replace(/-/g,"")}`;db.exec(`SAVEPOINT ${e}`);try{const r=n();return db.exec(`RELEASE SAVEPOINT ${e}`),r}catch(r){throw db.exec(`ROLLBACK TO SAVEPOINT ${e}`),db.exec(`RELEASE SAVEPOINT ${e}`),r}}o(withGraphTransaction,"withGraphTransaction");function collectNodes(n){return Array.isArray(n?.pages)&&n.pages.length?n.pages.flatMap(e=>e.nodes??[]):n?.nodes??[]}o(collectNodes,"collectNodes");function removeWorkflowScope(n){const e=workflowEntityId(n),r=`node_instance:${n}:`;db.prepare("DELETE FROM edges WHERE source_id = ? OR source_id LIKE ?").run(e,`${r}%`),db.prepare("DELETE FROM entities WHERE id = ? OR (type = 'node_instance' AND id LIKE ?)").run(e,`${r}%`)}o(removeWorkflowScope,"removeWorkflowScope");function reindexWorkflow(n){withGraphTransaction(()=>{removeWorkflowScope(n);const e=db.prepare(`
      SELECT w.*, u.name AS owner_name FROM workflows w JOIN users u ON u.id = w.owner_id WHERE w.id = ?
    `).get(n);if(!e)return;const r=workflowEntityId(n);upsertEntity.run(r,ENTITY_TYPES.WORKFLOW,e.name,e.owner_id,JSON.stringify({visibility:e.visibility}));const a=userEntityId(e.owner_id);upsertEntity.run(a,ENTITY_TYPES.USER,e.owner_name,e.owner_id,null),insertEdge.run(crypto.randomUUID(),r,a,RELATIONS.CREATED_BY,null);let s;try{s=JSON.parse(e.payload)}catch(t){console.warn(`[graph/indexer] workflow ${n}: payload kh\xF4ng parse \u0111\u01B0\u1EE3c JSON`,t.message);return}for(const t of collectNodes(s))try{if(!t?.id||!t?.type)continue;const i=nodeInstanceEntityId(n,t.id),d=nodePackageEntityId(t.type),c=t.data?.manifest?.name||t.type;upsertEntity.run(i,ENTITY_TYPES.NODE_INSTANCE,c,null,JSON.stringify({nodeType:t.type})),upsertEntity.run(d,ENTITY_TYPES.NODE_PACKAGE,c,null,null),insertEdge.run(crypto.randomUUID(),r,i,RELATIONS.CONTAINS,null),insertEdge.run(crypto.randomUUID(),i,d,RELATIONS.USES,null)}catch(i){console.warn(`[graph/indexer] workflow ${n}: b\u1ECF qua node l\u1ED7i ${t?.id}`,i.message)}})}o(reindexWorkflow,"reindexWorkflow"),module.exports={reindexWorkflow,removeWorkflowScope,withGraphTransaction};
