const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const db = new DatabaseSync(':memory:');
db.exec("PRAGMA foreign_keys=ON; CREATE TABLE users(id TEXT PRIMARY KEY); INSERT INTO users VALUES ('owner'), ('other')");
require('./schema').ensureVideoSchema(db);
require.cache[require.resolve('../db')] = { id: require.resolve('../db'), filename: require.resolve('../db'), loaded: true, exports: db };
const projects = require('../routes/video-projects');
const versions = require('../routes/video-versions').service;
const service = require('../routes/video-automation').service;
const { canonicalJson } = require('../../shared/video-document-diff');
const doc = { schemaVersion: 1, resolution: { width: 160, height: 160 }, fps: 24, audioRate: 48000, sequence: { markers: [] }, transitions: [], tracks: [
  { id: 'visual', name: 'Demo', type: 'video', order: 0, visible: true, muted: false, locked: false, clips: [{ id: 'shot', assetId: 'media', sourceInMs: 0, sourceOutMs: 1000, timelineInMs: 0, timelineOutMs: 1000, speed: 1, transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, opacity: 1, rotation: 0 }, effects: [], keyframes: [] }] },
  { id: 'captions', name: 'Disclaimer', type: 'caption', order: 1, visible: true, muted: false, locked: false, clips: [{ id: 'subtitle', text: 'Original dialogue', timelineInMs: 0, timelineOutMs: 1000, style: {} }] },
] };
db.prepare('INSERT INTO video_projects(id, owner_id, name, payload) VALUES (?, ?, ?, ?)').run('manual', 'owner', 'Manual', JSON.stringify(doc));
db.prepare('INSERT INTO video_project_snapshots(id, project_id, seq, payload) VALUES (?, ?, 0, ?)').run('initial', 'manual', JSON.stringify(doc));
for (const [id, owner, duration] of [['media', 'owner', 1000], ['short', 'owner', 200], ['foreign', 'other', 1000]]) db.prepare('INSERT INTO video_assets(id, owner_id, source_path, content_hash, duration_ms, kind, status) VALUES (?, ?, ?, ?, ?, ?, ?)').run(id, owner, `${id}.mp4`, `${id}-hash`, duration, 'video', 'ok');
async function main() { try {
  const pin = versions.create('owner', 'manual', { name: 'Source pin', baseRevision: 0 });
  const recipe = service.recipe('owner', { projectId: 'manual', versionId: pin.id, name: 'Demo recipe' });
  const create = (name, assignments = []) => service.createVariant('owner', { recipeId: recipe.id, name, assignments, idempotencyKey: name });
  const left = create('First', [{ clipId: 'subtitle', text: 'First variant' }]);
  const right = create('Second');
  const third = create('Third');
  assert.deepEqual(service.compile('owner', left.creativeVersionId), service.compile('owner', left.creativeVersionId), 'same pinned inputs produce identical document/plan/report');
  assert.equal(create('First', [{ clipId: 'subtitle', text: 'First variant' }]).projectId, left.projectId, 'retry cannot duplicate timeline or inputs');
  assert.throws(() => create('First'), e => e.status === 409);
  const inputCount = () => db.prepare('SELECT COUNT(*) AS n FROM video_automation_inputs').get().n;
  const before = inputCount();
  assert.throws(() => create('Short', [{ clipId: 'shot', assetId: 'short' }]), /quá ngắn/);
  assert.equal(inputCount(), before, 'failed compile rolls back input versions as well');
  assert.throws(() => create('Foreign', [{ clipId: 'shot', assetId: 'foreign' }]), /Media/);
  assert.throws(() => service.context('other', left.projectId), e => e.status === 404);
  const editCaption = (id, from, to) => projects.applyCommand(id, { type: 'SetProperty', args: { path: ['tracks', 1, 'clips', 0, 'text'], from, to } });
  editCaption(left.projectId, 'First variant', 'Edited subtitle');
  const ctx = service.context('owner', left.projectId);
  assert.equal(ctx.ledger.length, 1);
  assert.deepEqual(ctx.ledger[0].invalidates, ['subtitle']);
  assert.equal(ctx.ledger[0].preservesMedia, true);
  const request = { projectId: left.projectId, paths: [ctx.ledger[0].path], targetIds: [right.projectId, third.projectId] };
  const preview = service.preview('owner', request);
  assert.equal(preview.canApply, true, 'variant-specific baseline text is allowed when unedited');
  assert.equal(preview.targets[0].edits[0].from, 'Original dialogue');
  editCaption(third.projectId, 'Original dialogue', 'Own edit');
  assert.throws(() => service.applySiblings('owner', { ...request, impactHash: preview.impactHash, idempotencyKey: 'stale' }), e => e.status === 409);
  assert.equal(projects.getLatestCommandSeq(right.projectId), 0, 'conflict in second target never mutates first');
  editCaption(third.projectId, 'Own edit', 'Original dialogue');
  const fresh = service.preview('owner', request);
  db.exec(`CREATE TRIGGER fail_sibling BEFORE UPDATE ON video_projects WHEN NEW.id = '${third.projectId}' BEGIN SELECT RAISE(ABORT, 'disk full'); END`);
  const applyRequest = { ...request, impactHash: fresh.impactHash, idempotencyKey: 'apply' };
  assert.throws(() => service.applySiblings('owner', applyRequest), /disk full/);
  assert.equal(projects.getLatestCommandSeq(right.projectId), 0, 'mid-write failure rolls back the first target and operation');
  db.exec('DROP TRIGGER fail_sibling');
  const applied = service.applySiblings('owner', applyRequest);
  assert.equal(service.applySiblings('owner', applyRequest).operationId, applied.operationId);
  assert.equal(projects.recoverProjectState(third.projectId).tracks[1].clips[0].text, 'Edited subtitle');
  service.undoOperation('owner', { operationId: applied.operationId, idempotencyKey: 'undo-apply' });
  assert.equal(projects.recoverProjectState(right.projectId).tracks[1].clips[0].text, 'Original dialogue');
  assert.equal(projects.recoverProjectState(third.projectId).tracks[1].clips[0].text, 'Original dialogue');
  const editedDoc = projects.recoverProjectState(left.projectId);
  const reset = service.reset('owner', { projectId: left.projectId, baseRevision: ctx.seq, idempotencyKey: 'reset' });
  assert.equal(service.context('owner', left.projectId).ledger.length, 0);
  service.undoOperation('owner', { operationId: reset.operationId, idempotencyKey: 'undo-reset' });
  assert.equal(canonicalJson(projects.recoverProjectState(left.projectId)), canonicalJson(editedDoc), 'reset survives serialized undo/replay');
  const promoted = service.promoteComponent('owner', { projectId: left.projectId, clipId: 'subtitle', baseRevision: projects.getLatestCommandSeq(left.projectId), name: 'Subtitle component v2', idempotencyKey: 'component' });
  const oldCreative = service.input('owner', left.creativeVersionId, 'creative-variant');
  const newCreative = service.input('owner', promoted.creativeVersionId, 'creative-variant');
  assert.equal(newCreative.payload.components.shot, oldCreative.payload.components.shot, 'unrelated media component pin preserved');
  assert.notEqual(newCreative.payload.components.subtitle, oldCreative.payload.components.subtitle);
  assert.equal(service.context('owner', promoted.projectId).ledger.length, 0, 'new component is the new baseline');
  const editedPin = versions.create('owner', left.projectId, { name: 'Edited', baseRevision: projects.getLatestCommandSeq(left.projectId) });
  assert.equal(editedPin.origin.creativeVariantVersionId, left.creativeVersionId);
  const recipeV2 = service.recipe('owner', { projectId: left.projectId, versionId: editedPin.id, name: 'Recipe v2', parentId: recipe.id });
  assert.equal(recipeV2.parentId, recipe.id);
  const compileNode = require('../../nodes/composition-compile/execute');
  const nodeOutput = await compileNode({ creative_variant: { kind: 'CreativeVariantVersionRef', versionId: left.creativeVersionId } }, {}, { userId: 'owner' });
  const repeatedNode = await compileNode({}, { creativeVersionId: left.creativeVersionId }, { userId: 'owner' });
  assert.deepEqual(nodeOutput, repeatedNode, 'workflow compilation is idempotent and pinned');
  const editorOutput = await require('../../nodes/video-editor-workbench/execute')({ timeline_collection: nodeOutput.timeline_collection }, {}, { userId: 'owner' });
  assert.equal(editorOutput.timeline_collection.version.documentRef.tracks[1].clips[0].text, 'First variant');
  await assert.rejects(() => compileNode({}, { creativeVersionId: left.creativeVersionId }, { userId: 'other' }), e => e.status === 404);
  db.exec("UPDATE video_assets SET content_hash = 'replaced' WHERE id = 'media'");
  assert.throws(() => create('Changed source'), /đã thay đổi/);
  assert.throws(() => service.compile('owner', left.creativeVersionId), /đã thay đổi/);
  console.log('PASS automation: deterministic pinned compiler, manual producer, ownership, exact dependencies, atomic conflict/failure rollback, retry, reset/undo, component/recipe forks and version lineage');
} finally { db.close(); } }
main().catch(e => { console.error(e); process.exitCode = 1; });
