const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const db = new DatabaseSync(':memory:');
db.exec("PRAGMA foreign_keys=ON; CREATE TABLE users(id TEXT PRIMARY KEY); INSERT INTO users VALUES ('owner'), ('other')");
require('./schema').ensureVideoSchema(db);
require('./schema').ensureVideoSchema(db);
require.cache[require.resolve('../db')] = { id: require.resolve('../db'), filename: require.resolve('../db'), loaded: true, exports: db };
const projects = require('../routes/video-projects');
const service = require('../routes/video-batch').service;
const assets = require('../routes/video-assets');
const versions = require('../routes/video-versions').service;
const clone = value => JSON.parse(JSON.stringify(value));
for (const [id, kind, status, owner] of [['v1','video','ok','owner'], ['v2','video','ok','owner'], ['image','image','ok','owner'], ['audio','audio','ok','owner'], ['offline','video','offline','owner'], ['foreign','video','ok','other']]) {
  db.prepare('INSERT INTO video_assets(id, owner_id, source_path, content_hash, duration_ms, kind, status) VALUES (?, ?, ?, ?, ?, ?, ?)')
    .run(id, owner, `${id}/same-name.mp4`, id.startsWith('v') ? 'same-hash' : id, 2000, kind, status);
}
const makeItem = (id, mediaId = id) => ({ id, sourceRef: { kind: 'media', assetId: mediaId, contentHash: mediaId.startsWith('v') ? 'same-hash' : mediaId }, rating: 0, manualOrder: 0, enabled: true });
const save = p => service.save('owner', p.id, { expectedRevision: p.revision, name: p.name, draft: p.draft });
async function main() { try {
  let p = service.create('owner', { id: 'lab', name: 'Creative test' });
  assert.equal(service.create('owner', { id: 'lab', name: 'Creative test' }).collectionId, p.collectionId);
  assert.throws(() => service.create('owner', { id: 'lab', name: 'Different intent' }), e => e.status === 409);
  assert.throws(() => service.create('other', { id: 'lab', name: 'Creative test' }), e => e.status === 404);
  assert.deepEqual(service.list('other'), []);
  assert.throws(() => service.get('other', p.id), e => e.status === 404);
  p.draft.lists.push({ id: 'hook', name: 'Hook', minRating: 0, items: ['v1','v2','image','audio','offline'].map(id => makeItem(id)) });
  delete p.draft.lists[0].items[0].rating;
  delete p.draft.lists[0].items[0].enabled;
  p = save(p);
  assert.equal(p.draft.lists[0].items[0].rating,0);
  assert.equal(p.draft.lists[0].items[0].enabled,true);
  assert.equal(p.counts.hook, 4); assert.equal(p.draft.lists[0].items.length, 5);
  assert.equal(p.draft.lists[0].items[0].sourceRef.contentHash, p.draft.lists[0].items[1].sourceRef.contentHash, 'same hash paths stay separate');
  assert.equal((await assets.deleteAsset('v1','owner')).status, 409);
  const old = clone(p);
  p.draft.lists[0].items[0].rating = 5; p.draft.lists[0].minRating = 4;
  p = save(p); assert.equal(p.counts.hook, 1);
  assert.throws(() => save(old), e => e.status === 409);
  const bad = clone(p); bad.draft.lists[0].items.push(makeItem('foreign'));
  assert.throws(() => save(bad), e => e.status === 404);
  assert.deepEqual(service.get('owner',p.id),p);
  const invalid = clone(p); invalid.name = 'Rollback name'; invalid.draft.lists[0].items[0].rating = 6;
  assert.throws(() => save(invalid), /Item/); assert.equal(service.get('owner',p.id).name, p.name);
  db.exec("CREATE TRIGGER fail_lab_save BEFORE UPDATE ON video_batch_projects BEGIN SELECT RAISE(ABORT, 'disk full'); END");
  const failed = clone(p); failed.name = 'Must rollback'; assert.throws(() => save(failed), /disk full/);
  db.exec('DROP TRIGGER fail_lab_save'); assert.equal(service.get('owner',p.id).name, p.name);
  db.prepare('UPDATE video_timeline_collections SET name = ? WHERE id = ?').run('Rename from editor', p.collectionId);
  assert.throws(() => save(p), e => e.status === 409); p = service.get('owner',p.id);
  const prepared = service.prepare('owner',p.id,{ expectedRevision:p.revision, listId:'hook', itemId:'v1' });
  p = prepared.project;
  const preparationRequest = { expectedRevision:p.revision, listId:'hook', itemId:'v1' };
  assert.equal(service.prepare('owner',p.id,preparationRequest).timelineId,prepared.timelineId);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM video_projects').get().n,1);
  assert.equal(db.prepare('SELECT collection_id FROM video_projects WHERE id = ?').get(prepared.timelineId).collection_id,p.collectionId);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM video_render_jobs').get().n,0);
  projects.applyCommand(prepared.timelineId,{ type:'SetProperties', args:{ changes:[
    { path:['tracks',0,'clips',0,'sourceOutMs'], from:2000,to:1000 },
    { path:['tracks',0,'clips',0,'timelineOutMs'], from:2000,to:1000 },
  ] } });
  assert.equal(service.get('owner',p.id).media.v1.preparationPending,true);
  assert.equal(service.get('owner',p.id).counts.hook,0);
  assert.throws(() => service.capture('owner',p.id,{ ...preparationRequest,baseRevision:0 }),e=>e.status===409);
  p = service.capture('owner',p.id,{ ...preparationRequest,baseRevision:1 });
  const trimmed = clone(p.draft.lists[0].items[0].sourceRef.trim);
  assert.equal(trimmed.sourceOutMs,1000); assert.equal(p.counts.hook,1);
  const pin = versions.get('owner',prepared.timelineId,trimmed.versionId);
  assert.equal(pin.seq,1);
  projects.applyCommand(prepared.timelineId,{ type:'SetProperty', args:{ path:['tracks',0,'clips',0,'transform','opacity'],from:1,to:.5 } });
  assert.throws(() => service.capture('owner',p.id,{ expectedRevision:p.revision,listId:'hook',itemId:'v1',baseRevision:2 }),e=>e.status===422);
  assert.deepEqual(service.get('owner',p.id).draft.lists[0].items[0].sourceRef.trim,trimmed);
  assert.equal(versions.get('owner',prepared.timelineId,trimmed.versionId).document.tracks[0].clips[0].transform.opacity,1);
  const forged = clone(p); forged.draft.lists[0].items[0].sourceRef.trim.sourceOutMs = 1999;
  assert.throws(()=>save(forged),/ghim qua/);
  const img = service.prepare('owner',p.id,{expectedRevision:p.revision,listId:'hook',itemId:'image'}); p=img.project;
  const imageState = projects.recoverProjectState(img.timelineId);
  const imageTrack = imageState.tracks[0], imageClip = imageTrack.clips[0];
  projects.applyCommand(img.timelineId,{type:'InsertClip',args:{trackId:imageTrack.id,index:1,clip:{...clone(imageClip),id:'second-image',sourceOutMs:1000,timelineInMs:5000,timelineOutMs:6000}}});
  assert.throws(()=>service.capture('owner',p.id,{expectedRevision:p.revision,listId:'hook',itemId:'image',baseRevision:1}),e=>e.status===422);
  projects.applyCommand(img.timelineId,{type:'AddTransition',args:{transition:{id:'test-transition',fromClipId:imageClip.id,toClipId:'second-image',type:'crossfade',durationMs:200}}});
  assert.throws(()=>service.capture('owner',p.id,{expectedRevision:p.revision,listId:'hook',itemId:'image',baseRevision:2}),e=>e.status===422);
  const audio = service.prepare('owner',p.id,{expectedRevision:p.revision,listId:'hook',itemId:'audio'}); p=audio.project;
  projects.archiveProject(audio.timelineId);
  const oldRevision=p.revision;
  db.exec(`CREATE TRIGGER fail_archive BEFORE UPDATE ON video_projects WHEN NEW.id = '${img.timelineId}' BEGIN SELECT RAISE(ABORT, 'archive failure'); END`);
  assert.throws(()=>service.archive('owner',p.id,{expectedRevision:oldRevision}),/archive failure/);
  db.exec('DROP TRIGGER fail_archive');
  assert.equal(db.prepare('SELECT archived_at FROM video_projects WHERE id = ?').get(prepared.timelineId).archived_at,null);
  p=service.archive('owner',p.id,{expectedRevision:oldRevision});
  assert.equal(service.list('owner').length,0); assert.equal(service.list('owner',true).length,1);
  assert.equal((await assets.deleteAsset('v2','owner')).status,409);
  assert.throws(()=>projects.permanentlyDeleteProject(prepared.timelineId),/ghim trong Lab/);
  assert.throws(()=>require('../routes/video-timeline-collections').permanentlyDeleteCollection(p.collectionId),/Batch Creative Lab/);
  p=service.archive('owner',p.id,{expectedRevision:p.revision,restore:true});
  assert.equal(db.prepare('SELECT archived_at FROM video_projects WHERE id = ?').get(prepared.timelineId).archived_at,null);
  assert.ok(db.prepare('SELECT archived_at FROM video_projects WHERE id = ?').get(audio.timelineId).archived_at,'independently archived timeline stays archived');
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM video_render_jobs').get().n,0);
  assert.throws(()=>service.prepare('other',p.id,{expectedRevision:p.revision,listId:'hook',itemId:'v1'}),e=>e.status===404);
  p.draft.lists[0].items = p.draft.lists[0].items.filter(i=>i.id!=='v2'); p=save(p);
  assert.equal((await assets.deleteAsset('v2','owner')).ok,true);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM video_named_versions').get().n,4,'source and accepted trim pins retained');
  console.log('PASS BCL-01: durable CAS, owner scope, archive/restore rollback, source guards, preparation and immutable trim, unsupported edits, zero renders');
} finally { db.close(); } }
main().catch(e=>{ console.error(e); process.exitCode=1; });
