const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const db = new DatabaseSync(':memory:');
db.exec("PRAGMA foreign_keys=ON; CREATE TABLE users(id TEXT PRIMARY KEY); INSERT INTO users VALUES ('owner'), ('other')");
require('./schema').ensureVideoSchema(db);
require.cache[require.resolve('../db')] = { id:require.resolve('../db'), filename:require.resolve('../db'), loaded:true, exports:db };
const projects=require('../routes/video-projects'), service=require('../routes/video-batch').service, versions=require('../routes/video-versions').service;
const clone = v => JSON.parse(JSON.stringify(v));
const save = p => service.save('owner',p.id,{expectedRevision:p.revision,name:p.name,draft:p.draft});
const jobs = () => db.prepare('SELECT COUNT(*) AS n FROM video_render_jobs').get().n;
async function main() { try {
  for(const [id,kind,duration] of [['video','video',2000],['voice','audio',2000],['proxy','video',3000]]) db.prepare("INSERT INTO video_assets(id,owner_id,source_path,content_hash,duration_ms,kind,status) VALUES (?,'owner',?,?,?,?, 'ok')").run(id,`${id}.mp4`,id,duration,kind);
  let p=service.create('owner',{id:'prepared-lab',name:'Prepared Lab'});
  p.draft.lists=[{id:'list',name:'Prepared',minRating:0,items:[{id:'item',sourceRef:{kind:'media',assetId:'video',contentHash:'video'},rating:5}]}];p=save(p);
  const preparation=service.prepare('owner',p.id,{expectedRevision:p.revision,listId:'list',itemId:'item'});p=preparation.project;
  const timelineId=preparation.timelineId, original=projects.recoverProjectState(timelineId), first=original.tracks[0].clips[0];
  projects.applyCommand(timelineId,{type:'InsertClip',args:{trackId:original.tracks[0].id,index:1,clip:{...clone(first),id:'second',sourceOutMs:1000,timelineInMs:2000,timelineOutMs:3000}}});
  projects.applyCommand(timelineId,{type:'AddTrack',args:{track:{id:'voice-track',type:'audio',name:'Voice',order:1,muted:false,visible:true,locked:false,clips:[]}}});
  projects.applyCommand(timelineId,{type:'InsertClip',args:{trackId:'voice-track',index:0,clip:{...clone(first),id:'voice-clip',assetId:'voice',sourceInMs:250,sourceOutMs:1250,timelineInMs:1000,timelineOutMs:2000}}});
  let captured=service.capturePrepared('owner',p.id,{expectedRevision:p.revision,listId:'list',itemId:'item',baseRevision:3});p=captured.project;
  assert.equal(jobs(),0);assert.equal(p.draft.lists[0].items[0].sourceRef.kind,'timeline-version');
  const ref=clone(p.draft.lists[0].items[0].sourceRef);
  assert.equal(p.media.item.durationMs,3000);assert.equal(p.counts.list,1);
  p.draft.tracks=[{id:'main',name:'Main',type:'video',slots:[{id:'prepared-slot',listId:'list',vary:false,durationFrames:90}]}];p=save(p);
  const pre=service.preflight('owner',p.id,{expectedRevision:p.revision});assert.deepEqual(pre.issues,[]);
  const sample=service.sample('owner',p.id,{expectedRevision:p.revision});
  assert.equal(sample.document.tracks.filter(t=>t.type==='video').length,1);
  assert.equal(sample.document.tracks.filter(t=>t.type==='audio').length,1);
  const clips=sample.document.tracks.flatMap(t=>t.clips);assert.equal(clips.length,3);
  const voice=clips.find(c=>c.assetId==='voice');assert.equal(voice.sourceInMs,250);assert.equal(voice.sourceOutMs,1250);assert.equal(voice.timelineInMs,1000);
  assert.ok(clips.every(c=>!c.compoundRef));assert.ok(Object.values(sample.origins).some(o=>o.sourceRef.versionId===ref.versionId));
  const run=service.createRun('owner',p.id,{expectedRevision:p.revision,inputHash:pre.inputHash,idempotencyKey:'prepared-run'});
  assert.equal(run.count,1);assert.equal(jobs(),0);
  projects.applyCommand(timelineId,{type:'SetProperty',args:{path:['tracks',0,'clips',0,'transform','opacity'],from:1,to:.5}});
  p=service.get('owner',p.id);assert.equal(p.media.item.hasNewerPreparation,true);assert.equal(p.counts.list,1,'saved pin remains usable when source head advances');
  assert.deepEqual(p.draft.lists[0].items[0].sourceRef,ref);
  assert.equal(versions.get('owner',timelineId,ref.versionId).document.tracks[0].clips[0].transform.opacity,1);
  captured=service.capturePrepared('owner',p.id,{expectedRevision:p.revision,listId:'list',itemId:'item',baseRevision:4,asVariant:true});p=captured.project;
  const variant=p.draft.lists[0].items[1];assert.equal(variant.rating,0);assert.equal(variant.originItemId,'item');assert.notEqual(variant.id,'item');assert.notEqual(variant.sourceRef.versionId,ref.versionId);assert.equal(jobs(),0);
  const before=versions.get('owner',run.items[0].timelineId,run.items[0].versionId);assert.equal(before.document.tracks.find(t=>t.type==='video').clips[0].transform.opacity,1);
  projects.applyCommand(timelineId,{type:'AddTransition',args:{transition:{id:'nested-transition',fromClipId:first.id,toClipId:'second',type:'crossfade',durationMs:500}}});
  captured=service.capturePrepared('owner',p.id,{expectedRevision:p.revision,listId:'list',itemId:variant.id,baseRevision:5});p=captured.project;
  assert.equal(p.media[variant.id].needsProxy,true);assert.equal(jobs(),0,'unsupported save also does not render');
  p.draft.tracks[0].slots[0].fixedItemId=variant.id;p=save(p);
  assert.match(service.preflight('owner',p.id,{expectedRevision:p.revision}).issues[0].message,/Cần render trung gian/);
  let calls=0;
  const fakeRender=(owner,projectId,options)=>{calls++;db.prepare("INSERT INTO video_render_jobs(id,project_id,owner_id,pinned_seq,preset_id,status,manifest_json) VALUES ('proxy-job',?,?,?,'original','done','{}')").run(projectId,owner,options.baseRevision);return {jobId:'proxy-job'};};
  p=service.startProxy('owner',p.id,{expectedRevision:p.revision,listId:'list',itemId:variant.id},fakeRender);assert.equal(calls,1);assert.equal(jobs(),1);
  p=await service.acceptProxy('owner',p.id,{expectedRevision:p.revision,listId:'list',itemId:variant.id},async()=>db.prepare("SELECT * FROM video_assets WHERE id='proxy'").get());
  assert.equal(p.media[variant.id].proxyReady,true);assert.equal(p.draft.lists[0].items[1].sourceRef.kind,'timeline-version');
  p=service.startProxy('owner',p.id,{expectedRevision:p.revision,listId:'list',itemId:variant.id},fakeRender);assert.equal(calls,1,'verified proxy cache reused');
  assert.deepEqual(service.preflight('owner',p.id,{expectedRevision:p.revision}).issues,[]);
  const forged=clone(p);forged.draft.lists[0].items[1].sourceRef.seq=0;assert.throws(()=>save(forged),/Prepared pin/);
  assert.throws(()=>service.preparedDocument('other',p.id,{listId:'list',itemId:'item'}),e=>e.status===404);
  p.draft.lists[0].items=[];p.draft.tracks=[];p=save(p);
  assert.ok(require('./batchReferences').assetReference(db,'owner','video'),'run snapshot protects sources after removing list');
  assert.equal(require('./batchReferences').projectReference(db,timelineId),true,'run snapshot protects original prepared timeline');
  console.log('PASS prepared: save without render, immutable pins, three-clip expansion/windows/audio, variants, explicit proxy cache, run history and ownership');
} finally { db.close(); } }
main().catch(e=>{console.error(e);process.exitCode=1;});
