const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const db = new DatabaseSync(':memory:');
db.exec("PRAGMA foreign_keys=ON; CREATE TABLE users(id TEXT PRIMARY KEY); INSERT INTO users VALUES ('owner'), ('other')");
require('./schema').ensureVideoSchema(db);
require.cache[require.resolve('../db')] = { id: require.resolve('../db'), filename: require.resolve('../db'), loaded: true, exports: db };
const commands = require('../routes/video-projects');
const versions = require('../routes/video-versions').service;
const bulk = require('../routes/video-bulk-import');
const execute = require('../../nodes/video-editor-workbench/execute');
const { documentDiff } = require('../../shared/video-document-diff');
const clip = { id: 'c', assetId: 'a', sourceInMs: 0, sourceOutMs: 1000, timelineInMs: 0, timelineOutMs: 1000, speed: 1, effects: [], keyframes: [], transform: {} };
const document = { schemaVersion: 1, resolution: { width: 160, height: 160 }, fps: 24, audioRate: 48000, sequence: { markers: [] }, tracks: [{ id: 'v', type: 'video', visible: true, muted: true, locked: false, order: 0, clips: [clip] }], transitions: [] };
function project(id, owner = 'owner') {
  db.prepare('INSERT INTO video_projects(id, owner_id, name, payload) VALUES (?, ?, ?, ?)').run(id, owner, id, JSON.stringify(document));
  db.prepare('INSERT INTO video_project_snapshots(id, project_id, seq, payload) VALUES (?, ?, 0, ?)').run(id, id, JSON.stringify(document));
}
db.exec("INSERT INTO video_assets(id, owner_id, source_path, content_hash, kind, status, duration_ms) VALUES ('a', 'owner', 'fixture.mp4', 'original-hash', 'video', 'ok', 1000)");
project('p'); project('q'); project('other-p', 'other');
(async () => {
  assert.throws(() => versions.create('owner', 'p', { name: 'bad', baseRevision: 4 }), e => e.status === 409);
  const v = versions.create('owner', 'p', { name: 'Review 1', baseRevision: 0 });
  assert.equal(v.issues.length, 0);
  assert.throws(() => versions.get('other', 'p', v.id), e => e.status === 404);
  assert.throws(() => versions.get('owner', 'q', v.id), e => e.status === 404);
  versions.review('owner', 'p', v.id, { decision: 'approved', note: 'Checked output' });
  assert.equal(versions.get('owner', 'p', v.id).decisions[0].stale, false);
  await assert.rejects(() => execute({}, { projectId: 'p' }, { userId: 'owner' }), /ghim/);
  await assert.rejects(() => execute({}, { projectId: 'p', versionId: v.id }, {}), /người dùng/);
  await assert.rejects(() => execute({ timeline_collection: {} }, {}, { userId: 'owner' }), /TimelineCollectionRef/);
  commands.applyCommand('p', { type: 'SetProperty', args: { path: ['tracks', 0, 'clips', 0, 'transform', 'x'], from: undefined, to: 10 }, baseRevision: 0 });
  const pin = await execute({}, { projectId: 'p', versionId: v.id }, { userId: 'owner' });
  assert.equal(pin.timeline_collection.version.documentRef.tracks[0].clips[0].transform.x, undefined);
  assert.equal(pin.timeline_collection.staleDraft, true);
  db.prepare("INSERT INTO video_render_jobs(id, project_id, owner_id, status, lease_until) VALUES ('busy', 'p', 'owner', 'running', ?)").run(Date.now() + 60000);
  const { createRenderJob } = require('../routes/video-render');
  const renderPin = createRenderJob('owner', 'p', { versionId: v.id, idempotencyKey: 'compare-v1' });
  assert.equal(db.prepare('SELECT pinned_seq FROM video_render_jobs WHERE id = ?').get(renderPin.jobId).pinned_seq, 0);
  assert.equal(createRenderJob('owner', 'p', { versionId: v.id, idempotencyKey: 'compare-v1' }).jobId, renderPin.jobId);
  assert.throws(() => createRenderJob('owner', 'p', { baseRevision: 1, idempotencyKey: 'compare-v1' }), e => e.status === 409);
  assert.throws(() => createRenderJob('other', 'p', { versionId: v.id }), e => e.status === 404);
  assert.throws(() => createRenderJob('owner', 'q', { versionId: v.id }), e => e.status === 404);
  assert.equal(versions.get('owner', 'p', v.id).decisions[0].stale, true);
  assert.throws(() => versions.review('owner', 'p', v.id, { decision: 'approved' }), e => e.status === 409);
  assert.equal(versions.compare('owner', 'p', v.id).changes[0].path, '/tracks/v/clips/c/transform/x');
  assert.equal(documentDiff({ tracks: [{ id: 'a' }, { id: 'b' }] }, { tracks: [{ id: 'b' }, { id: 'a' }] }).length, 0);
  db.exec("UPDATE video_assets SET content_hash='changed' WHERE id='a'");
  assert.equal(versions.get('owner', 'p', v.id).staleDependencies, true);
  assert.throws(() => createRenderJob('owner', 'p', { versionId: v.id }), e => e.status === 409);
  await assert.rejects(() => execute({}, { projectId: 'p', versionId: v.id }, { userId: 'owner' }), /Media/);
  db.exec("UPDATE video_assets SET content_hash='original-hash', rights_json='{\"expiresAt\":\"2000-01-01\"}' WHERE id='a'");
  assert.ok(versions.get('owner', 'p', v.id).issues.some(i => i.path === '/tracks/v/clips/c' && i.severity === 'error'));
  console.log('PASS named pins: ownership, immutable workflow, typed refs, content/dependency staleness, review QC and semantic locators');
  const options = { placement: 'new_tracks' };
  const op = bulk.createBulkImportOperation('owner', { timelineIds: ['p', 'q'], orderedAssetIds: ['a'], options });
  assert.equal(op.status, 'completed');
  bulk.undoBulkImportOperation('owner', op.id);
  assert.equal(commands.recoverProjectState('p').tracks.length, 1);
  assert.equal(commands.recoverProjectState('q').tracks.length, 1);
  assert.equal(bulk.undoBulkImportOperation('owner', op.id).status, 'undone');
  assert.throws(() => bulk.retryBulkImportOperation('owner', op.id), /hoàn tác/);
  const op2 = bulk.createBulkImportOperation('owner', { timelineIds: ['p', 'q'], orderedAssetIds: ['a'], options });
  const beforeP = commands.getLatestCommandSeq('p');
  commands.applyCommand('q', { type: 'SetProperty', args: { path: ['tracks', 0, 'clips', 0, 'transform', 'y'], from: undefined, to: 10 } });
  assert.throws(() => bulk.undoBulkImportOperation('owner', op2.id), e => e.status === 409);
  assert.equal(commands.getLatestCommandSeq('p'), beforeP, 'conflict on second timeline leaves first untouched');
  assert.throws(() => bulk.previewBulkImport('owner', { timelineIds: ['p'], orderedAssetIds: ['a'], options: { placement: 'at_time', startMs: 0 } }), /trùng/);
  assert.equal(bulk.previewBulkImport('owner', { timelineIds: ['q'], orderedAssetIds: ['a'], options: { placement: 'at_time', startMs: 5000 } }).targets[0].placements[0].startMs, 5000);
  console.log('PASS bulk: new tracks, gap collision, atomic cross-timeline undo, repeat undo, stale revision rollback');
})().catch(e => { console.error(e); process.exitCode = 1; }).finally(() => db.close());
