const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const { ensureVideoSchema } = require('./schema');
const { createRenderLifecycle } = require('./renderLifecycle');
const db = new DatabaseSync(':memory:');
db.exec("CREATE TABLE users(id TEXT PRIMARY KEY); INSERT INTO users VALUES ('a'), ('b')");
ensureVideoSchema(db);
db.exec("INSERT INTO video_projects(id, owner_id, name, payload) VALUES ('p', 'a', 'A', '{}'), ('q', 'b', 'B', '{}')");
let time = 1000;
const life = createRenderLifecycle(db, () => time);
const add = (id, project = 'p', owner = 'a') => db.prepare('INSERT INTO video_render_jobs(id, project_id, owner_id) VALUES (?, ?, ?)').run(id, project, owner);
const row = id => db.prepare('SELECT * FROM video_render_jobs WHERE id = ?').get(id);
add('one'); add('two'); add('other', 'q', 'b');
const first = life.claim('one');
assert.ok(first);
assert.equal(life.claim('two'), null, 'one live lease per owner');
assert.ok(life.claim('other'), 'another owner can run independently');
assert.equal(life.recoverExpired(), 0, 'never steal a live worker');
time += 46000;
assert.equal(life.recoverExpired(), 2);
const second = life.claim('one');
assert.notEqual(second, first);
assert.throws(() => life.assertCurrent('one', first), e => e.staleAttempt);
assert.equal(life.heartbeat('one', first), 0);
assert.equal(life.heartbeat('one', second), 1);
life.cancel('one');
assert.throws(() => life.assertCurrent('one', second), e => e.cancelled, 'cancel also fences verify/promote');
time += 46000;
life.recoverExpired();
assert.equal(row('one').status, 'cancelled');
life.cancel('two');
assert.equal(row('two').status, 'cancelled');
add('exhaust');
for (let n = 0; n < 3; n++) { assert.ok(life.claim('exhaust')); time += 46000; life.recoverExpired(); }
assert.equal(row('exhaust').status, 'error');
assert.equal(row('exhaust').attempt_count, 3);
assert.equal(life.claim('exhaust'), null);
db.close();
console.log('PASS — render lease, owner concurrency, fencing, cancellation and bounded restart recovery');
