const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { createSourceReceiver, transferSource } = require('./sourceTransfer');
const base = path.resolve(__dirname, '../../logs/source-transfer-proof');
fs.mkdirSync(base, { recursive: true });
const root = fs.mkdtempSync(path.join(base, 'case-'));
const receiver = createSourceReceiver(path.join(root, 'agent'));
const source = path.join(root, 'server.mp4');
const data = crypto.randomBytes(2200000);
fs.writeFileSync(source, data);
(async () => {
  const calls = [];
  const run = async (kind, payload) => { calls.push(kind); return receiver(kind, JSON.parse(JSON.stringify(payload))); };
  const output = await transferSource(source, run);
  assert.equal(path.dirname(output), path.join(root, 'agent'));
  assert.deepEqual(fs.readFileSync(output), data);
  assert.equal(calls.filter(k => k === 'source-chunk').length, 3);
  calls.length = 0;
  assert.equal(await transferSource(source, run), output);
  assert.deepEqual(calls, ['source-begin'], 'verified cache skips transfer');
  const params = { transferId: crypto.randomUUID(), hash: 'a'.repeat(64), size: 4, extension: '.mp4' };
  await assert.rejects(receiver('source-begin', { ...params, transferId: '../escape' }), /identity/);
  await receiver('source-begin', params);
  await assert.rejects(receiver('source-chunk', { ...params, offset: 1, chunk: 'YQ==' }), /offset/);
  await receiver('source-chunk', { ...params, offset: 0, chunk: Buffer.from('xxxx').toString('base64') });
  await assert.rejects(receiver('source-finish', params), /checksum/);
  await receiver('source-abort', params);
  const blockedMeta = { ...params, transferId: crypto.randomUUID() };
  const metaPath = path.join(root, 'agent', `${blockedMeta.transferId}.json`);
  fs.mkdirSync(metaPath);
  await assert.rejects(receiver('source-begin', blockedMeta));
  assert.equal(fs.existsSync(path.join(root, 'agent', `${blockedMeta.transferId}.partial`)), false, 'failed begin never leaves a new partial');
  fs.rmdirSync(metaPath);
  const partials = fs.readdirSync(path.join(root, 'agent')).filter(p => p.endsWith('.partial'));
  assert.equal(partials.length, 0);
  fs.writeFileSync(source, crypto.randomBytes(2100000));
  let ticks = 0;
  await assert.rejects(transferSource(source, run, () => { if (++ticks > 2) throw new Error('cancelled'); }), /cancelled/);
  assert.equal(fs.readdirSync(path.join(root, 'agent')).filter(p => p.endsWith('.partial')).length, 0);
  console.log('PASS source relay: bounded serialized chunks, isolated agent cache, SHA-256, reuse, traversal/offset rejection, abort cleanup');
})().catch(e => { console.error(e); process.exitCode = 1; }).finally(() => {
  assert.equal(path.dirname(path.resolve(root)), base);
  fs.rmSync(root, { recursive: true, force: true });
});
