import assert from 'node:assert/strict';
import { createPresenceClock } from './analyticsPresence.js';
import { analyticsCommand } from './analyticsCommands.js';
const flags={visible:true,focused:true,pointer:false,viewing:false,waiting:true};
const clock=createPresenceClock({mono:0,wall:100000,flags,idleMs:2500});
clock.advance(0,100000,flags,true);
const a=clock.advance(1000,101000);assert.equal(a.intervals[0].engaged,true);assert.equal(a.intervals[0].pointer,false,'keyboard use needs no pointer');
const b=clock.advance(3000,103000);assert.deepEqual(b.intervals.map(x=>[x.end-x.start,x.engaged]),[[1500,true],[500,false]]);
clock.advance(4000,104000,{...flags,visible:false,focused:false});
assert.equal(clock.advance(5000,105000).intervals[0].visible,false);
const gap=clock.advance(65000,165000);assert.equal(gap.intervals.length,0);assert.equal(gap.missingMs,60000);
clock.advance(66000,166000,flags,true);
assert.equal(clock.advance(67000,167000).intervals[0].engaged,true);
assert.equal(clock.advance(68000,200000).intervals.length,0,'wall/monotonic mismatch is missing');
assert.equal(analyticsCommand('/api/video-batch/id/prepare','POST').command,'prepare');
assert.equal(analyticsCommand('/api/video-batch/id/runs','POST').command,'generate');
assert.equal(analyticsCommand('/api/video-render/id/render','POST').command,'render');
assert.equal(analyticsCommand('/api/sheets/id','PUT'),null,'autosave excluded');
assert.equal(analyticsCommand('/api/video-batch/id','GET'),null,'poll excluded');
assert.equal(analyticsCommand('/api/analytics/events','POST'),null,'no recursive tracking');
console.log('Analytics presence and semantic command boundaries passed');
